- name: Make sure universe repository is enabled
  apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu focal universe
    state: present
    update_cache: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Enable Longsleep's PPA
  apt_repository:
    repo: ppa:longsleep/golang-backports
    state: present
    update_cache: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install golang
  package:
    name: golang-go
    state: latest

- name: Add go related environment variables to .bashrc
  blockinfile:
    destfile: ~/.bashrc
    insertafter: EOF
    marker: "# golang {mark} "
    block: |
      GO111MODULE=auto
      export GOROOT={{ goroot_parent_path }}/go
      export GOPATH=$HOME/go
      export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
