---
#- hosts: gcn
- hosts: default
  tasks:
    - name: Ensure group "alex" exists with correct gid
      group:
        name: alex
        state: present
        gid: 1010
  roles:
    - weareinteractive.users
  vars:
    users:
      - username: alex
        password: "$6$jqaKaHu2aMmRdrBl$7SJc30OspJFxMucislqfhKY2WjyIfCw.B3x8qeyx08Y8Nre8XqTmRXUXL0dWzrWdQK3yEJe9tVLwYFAe4CWWh."
        group: "alex"
        shell: /bin/bash
        home_create: yes
        authorized_keys:
          - "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
          - "{{ lookup('file', '~/.ssh/winwisely268.pub') }}"
          - "{{ lookup('file', '~/.ssh/gutterbacon.pub') }}"
