- name: Set includedir in sudoers
  lineinfile:
    dest: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    state: present
    validate: "/usr/sbin/visudo -cf %s"

- name: Add user to sudoers.d
  lineinfile:
    path: "/etc/sudoers.d/{{ item }}"
    line: '{{ item }} ALL=(ALL) NOPASSWD: ALL'
    state: present
    mode: 0440
    create: yes
    validate: 'visudo -cf %s'
  with_items: "{{ sudoer_users | default([]) }}"